HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls'))
]

rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index')
]

rides/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
  first_name = models.CharField(max_length=64)
  origination = models.CharField(max_length=64)
  destination_city = models.CharField(max_length=64)
  destination_state = models.CharField(max_length=2)
  date = models.DateField()
  time = models.TimeField()
  taking_passengers = models.BooleanField(default=False)
  seats_available = models.IntegerField(default=0)

rides/forms.py
from django import forms


class RideForm(forms.Form):
  city = forms.CharField(label='City', max_length=64, required=False)
  state = forms.CharField(label='State (2-letter code)', max_length=2, required=False)

rides/views.py
from django.shortcuts import render
from django.db.models import Q

from .models import Person
from .forms import RideForm


def index(request):
  context = {}
  
  city = request.GET.get('city', '').strip()
  state = request.GET.get('state', '').strip()
  
  people = Person.objects.all()
  
  if city or state:
    context["inputExists"] = True
    
    query_filters = Q()
    
    if city:
      query_filters &= (
        Q(origination__icontains=city) | 
        Q(destination_city__icontains=city)
      )
    
    if state:
      query_filters &= Q(destination_state__iexact=state)
    
    people = people.filter(query_filters)
    
    context["search_city"] = city
    context["search_state"] = state.upper()
  
  context["people"] = people
  context["form"] = RideForm()

  return render(request, "index_view.html", context)

rides/templates/index_view.html
{% extends "base.html" %}

{% block content %}
<div class="search-form"> 
  <h2>Search for Ride Share Partners</h2>
  <form action="{% url 'rides:index' %}" method="get">
    <table>
      <tr>
        <td>{{ form.city.label_tag }}</td>
        <td>{{ form.city }}</td>
      </tr>
      <tr>
        <td>{{ form.state.label_tag }}</td>
        <td>{{ form.state }}</td>
      </tr>
      <tr>
        <td colspan="2"><input type="submit" value="Search"></td>
      </tr>
    </table>
  </form>
</div>

{% if inputExists %}
<div class="results">
  <h3>Search Results
    {% if search_city and search_state %}
      for City: "{{ search_city }}" in State: "{{ search_state }}"
    {% elif search_city %}
      for City: "{{ search_city }}"
    {% elif search_state %}
      for State: "{{ search_state }}"
    {% endif %}
  </h3>
  
  {% if people %}
    <p>Found {{ people.count }} registrant(s)</p>
    <table border="1" cellpadding="5" cellspacing="0">
      <thead>
        <tr>
          <th>Name</th>
          <th>Origination</th>
          <th>Destination City</th>
          <th>Destination State</th>
          <th>Date</th>
          <th>Time</th>
          <th>Taking Passengers</th>
          <th>Seats Available</th>
        </tr>
      </thead>
      <tbody>
        {% for person in people %}
        <tr>
          <td>{{ person.first_name }}</td> 
          <td>{{ person.origination }}</td>
          <td>{{ person.destination_city }}</td> 
          <td>{{ person.destination_state }}</td> 
          <td>{{ person.date }}</td> 
          <td>{{ person.time }}</td> 
          <td>{% if person.taking_passengers %}Yes{% else %}No{% endif %}</td>
          <td>{{ person.seats_available }}</td> 
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p><em>No registrants found matching your search criteria.</em></p>
  {% endif %}
</div>
{% endif %}

{% endblock %}

templates/base.html
{% load static %}

<html>
<title> ORF 401: Spring 2022 </title>

<body bgcolor="white" text="black">
  <center>
    <h1>ORF 401</h1>
    <img src="{% static 'logo_youber.png' %}" alt="Image of logo" width="300">

    {% block content %}
    {% endblock %}

  </center>
</body>

</html>